# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Tue Oct  1 00:15:14 2013
#      by: PyQt5 UI code generator 5.0.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1190, 630)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("alternate-background-color: rgb(237, 255, 230);")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(True)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.twMenu = QtWidgets.QTabWidget(self.centralWidget)
        self.twMenu.setGeometry(QtCore.QRect(10, 20, 1171, 571))
        self.twMenu.setStyleSheet("font: 75 11pt \"Segoe UI\";")
        self.twMenu.setObjectName("twMenu")
        self.tab_Transacciones = QtWidgets.QWidget()
        self.tab_Transacciones.setObjectName("tab_Transacciones")
        self.rbCompra_t = QtWidgets.QRadioButton(self.tab_Transacciones)
        self.rbCompra_t.setGeometry(QtCore.QRect(280, 12, 81, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.rbCompra_t.setFont(font)
        self.rbCompra_t.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.rbCompra_t.setObjectName("rbCompra_t")
        self.rbVenta_t = QtWidgets.QRadioButton(self.tab_Transacciones)
        self.rbVenta_t.setGeometry(QtCore.QRect(210, 12, 61, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.rbVenta_t.setFont(font)
        self.rbVenta_t.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.rbVenta_t.setObjectName("rbVenta_t")
        self.txtFilterCliente_t = QtWidgets.QLineEdit(self.tab_Transacciones)
        self.txtFilterCliente_t.setGeometry(QtCore.QRect(120, 100, 201, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.txtFilterCliente_t.setFont(font)
        self.txtFilterCliente_t.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtFilterCliente_t.setObjectName("txtFilterCliente_t")
        self.cbFilterCliente_t = QtWidgets.QComboBox(self.tab_Transacciones)
        self.cbFilterCliente_t.setGeometry(QtCore.QRect(30, 100, 81, 22))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cbFilterCliente_t.setFont(font)
        self.cbFilterCliente_t.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.cbFilterCliente_t.setObjectName("cbFilterCliente_t")
        self.cbFilterCliente_t.addItem("")
        self.cbFilterCliente_t.addItem("")
        self.tvProductos_t = QtWidgets.QTableView(self.tab_Transacciones)
        self.tvProductos_t.setGeometry(QtCore.QRect(470, 130, 681, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tvProductos_t.setFont(font)
        self.tvProductos_t.setObjectName("tvProductos_t")
        self.txtFilterProducto_t = QtWidgets.QLineEdit(self.tab_Transacciones)
        self.txtFilterProducto_t.setGeometry(QtCore.QRect(580, 100, 201, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.txtFilterProducto_t.setFont(font)
        self.txtFilterProducto_t.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtFilterProducto_t.setObjectName("txtFilterProducto_t")
        self.cbFilterProducto_t = QtWidgets.QComboBox(self.tab_Transacciones)
        self.cbFilterProducto_t.setGeometry(QtCore.QRect(490, 100, 81, 22))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cbFilterProducto_t.setFont(font)
        self.cbFilterProducto_t.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.cbFilterProducto_t.setObjectName("cbFilterProducto_t")
        self.cbFilterProducto_t.addItem("")
        self.cbFilterProducto_t.addItem("")
        self.cbFilterProducto_t.addItem("")
        self.cbFilterProducto_t.addItem("")
        self.sbCantidadProducto_t = QtWidgets.QSpinBox(self.tab_Transacciones)
        self.sbCantidadProducto_t.setGeometry(QtCore.QRect(1020, 250, 71, 22))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sbCantidadProducto_t.setFont(font)
        self.sbCantidadProducto_t.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.sbCantidadProducto_t.setObjectName("sbCantidadProducto_t")
        self.tvDetalleTransaccion_t = QtWidgets.QTableView(self.tab_Transacciones)
        self.tvDetalleTransaccion_t.setGeometry(QtCore.QRect(10, 310, 1141, 131))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tvDetalleTransaccion_t.setFont(font)
        self.tvDetalleTransaccion_t.setObjectName("tvDetalleTransaccion_t")
        self.btnSumarProducto_t = QtWidgets.QPushButton(self.tab_Transacciones)
        self.btnSumarProducto_t.setGeometry(QtCore.QRect(1120, 250, 21, 23))
        self.btnSumarProducto_t.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Img/mas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSumarProducto_t.setIcon(icon)
        self.btnSumarProducto_t.setObjectName("btnSumarProducto_t")
        self.btnRestarProducto_t = QtWidgets.QPushButton(self.tab_Transacciones)
        self.btnRestarProducto_t.setGeometry(QtCore.QRect(1120, 450, 21, 23))
        self.btnRestarProducto_t.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Img/menos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRestarProducto_t.setIcon(icon1)
        self.btnRestarProducto_t.setObjectName("btnRestarProducto_t")
        self.btnAceptar_t = QtWidgets.QPushButton(self.tab_Transacciones)
        self.btnAceptar_t.setGeometry(QtCore.QRect(1050, 490, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnAceptar_t.setFont(font)
        self.btnAceptar_t.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Img/guardar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAceptar_t.setIcon(icon2)
        self.btnAceptar_t.setIconSize(QtCore.QSize(20, 20))
        self.btnAceptar_t.setObjectName("btnAceptar_t")
        self.btnCancelar_t = QtWidgets.QPushButton(self.tab_Transacciones)
        self.btnCancelar_t.setGeometry(QtCore.QRect(930, 490, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnCancelar_t.setFont(font)
        self.btnCancelar_t.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Img/borrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancelar_t.setIcon(icon3)
        self.btnCancelar_t.setIconSize(QtCore.QSize(20, 20))
        self.btnCancelar_t.setObjectName("btnCancelar_t")
        self.line1_t = QtWidgets.QFrame(self.tab_Transacciones)
        self.line1_t.setGeometry(QtCore.QRect(10, 50, 1151, 16))
        self.line1_t.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1_t.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1_t.setObjectName("line1_t")
        self.line2_t = QtWidgets.QFrame(self.tab_Transacciones)
        self.line2_t.setGeometry(QtCore.QRect(170, 280, 981, 20))
        self.line2_t.setFrameShape(QtWidgets.QFrame.HLine)
        self.line2_t.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line2_t.setObjectName("line2_t")
        self.label1_t = QtWidgets.QLabel(self.tab_Transacciones)
        self.label1_t.setGeometry(QtCore.QRect(10, 10, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label1_t.setFont(font)
        self.label1_t.setObjectName("label1_t")
        self.label2_t = QtWidgets.QLabel(self.tab_Transacciones)
        self.label2_t.setGeometry(QtCore.QRect(10, 70, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label2_t.setFont(font)
        self.label2_t.setObjectName("label2_t")
        self.label3_t = QtWidgets.QLabel(self.tab_Transacciones)
        self.label3_t.setGeometry(QtCore.QRect(470, 70, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label3_t.setFont(font)
        self.label3_t.setObjectName("label3_t")
        self.label4_t = QtWidgets.QLabel(self.tab_Transacciones)
        self.label4_t.setGeometry(QtCore.QRect(10, 275, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label4_t.setFont(font)
        self.label4_t.setObjectName("label4_t")
        self.label5_t = QtWidgets.QLabel(self.tab_Transacciones)
        self.label5_t.setGeometry(QtCore.QRect(930, 250, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label5_t.setFont(font)
        self.label5_t.setObjectName("label5_t")
        self.tvClientes_t = QtWidgets.QTableView(self.tab_Transacciones)
        self.tvClientes_t.setGeometry(QtCore.QRect(10, 130, 431, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tvClientes_t.setFont(font)
        self.tvClientes_t.setObjectName("tvClientes_t")
        self.twMenu.addTab(self.tab_Transacciones, "")
        self.tab_Pagos = QtWidgets.QWidget()
        self.tab_Pagos.setObjectName("tab_Pagos")
        self.tvCuentaCorriente_pag = QtWidgets.QTableView(self.tab_Pagos)
        self.tvCuentaCorriente_pag.setGeometry(QtCore.QRect(10, 50, 1141, 211))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tvCuentaCorriente_pag.setFont(font)
        self.tvCuentaCorriente_pag.setObjectName("tvCuentaCorriente_pag")
        self.tvDetalleTransaccion_pag = QtWidgets.QTableView(self.tab_Pagos)
        self.tvDetalleTransaccion_pag.setGeometry(QtCore.QRect(585, 301, 571, 161))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tvDetalleTransaccion_pag.setFont(font)
        self.tvDetalleTransaccion_pag.setObjectName("tvDetalleTransaccion_pag")
        self.btnAceptar_pag = QtWidgets.QPushButton(self.tab_Pagos)
        self.btnAceptar_pag.setGeometry(QtCore.QRect(1050, 490, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnAceptar_pag.setFont(font)
        self.btnAceptar_pag.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnAceptar_pag.setIcon(icon2)
        self.btnAceptar_pag.setIconSize(QtCore.QSize(20, 20))
        self.btnAceptar_pag.setObjectName("btnAceptar_pag")
        self.btnCancelar_pag = QtWidgets.QPushButton(self.tab_Pagos)
        self.btnCancelar_pag.setGeometry(QtCore.QRect(930, 490, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnCancelar_pag.setFont(font)
        self.btnCancelar_pag.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnCancelar_pag.setIcon(icon3)
        self.btnCancelar_pag.setIconSize(QtCore.QSize(20, 20))
        self.btnCancelar_pag.setObjectName("btnCancelar_pag")
        self.txtFilterPagos_pag = QtWidgets.QLineEdit(self.tab_Pagos)
        self.txtFilterPagos_pag.setGeometry(QtCore.QRect(110, 20, 201, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.txtFilterPagos_pag.setFont(font)
        self.txtFilterPagos_pag.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtFilterPagos_pag.setObjectName("txtFilterPagos_pag")
        self.cbFilterCliente_pag = QtWidgets.QComboBox(self.tab_Pagos)
        self.cbFilterCliente_pag.setGeometry(QtCore.QRect(10, 20, 91, 22))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cbFilterCliente_pag.setFont(font)
        self.cbFilterCliente_pag.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.cbFilterCliente_pag.setObjectName("cbFilterCliente_pag")
        self.cbFilterCliente_pag.addItem("")
        self.cbFilterCliente_pag.addItem("")
        self.label1_pag = QtWidgets.QLabel(self.tab_Pagos)
        self.label1_pag.setGeometry(QtCore.QRect(100, 310, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label1_pag.setFont(font)
        self.label1_pag.setObjectName("label1_pag")
        self.label4_pag = QtWidgets.QLabel(self.tab_Pagos)
        self.label4_pag.setGeometry(QtCore.QRect(420, 310, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label4_pag.setFont(font)
        self.label4_pag.setObjectName("label4_pag")
        self.label3_pag = QtWidgets.QLabel(self.tab_Pagos)
        self.label3_pag.setGeometry(QtCore.QRect(43, 370, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label3_pag.setFont(font)
        self.label3_pag.setObjectName("label3_pag")
        self.txtMonto_gt = QtWidgets.QLineEdit(self.tab_Pagos)
        self.txtMonto_gt.setGeometry(QtCore.QRect(230, 310, 121, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.txtMonto_gt.setFont(font)
        self.txtMonto_gt.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtMonto_gt.setObjectName("txtMonto_gt")
        self.cbFormaPago_pag = QtWidgets.QComboBox(self.tab_Pagos)
        self.cbFormaPago_pag.setGeometry(QtCore.QRect(190, 370, 161, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.cbFormaPago_pag.setFont(font)
        self.cbFormaPago_pag.setObjectName("cbFormaPago_pag")
        self.cbFormaPago_pag.addItem("")
        self.cbFormaPago_pag.addItem("")
        self.cbFormaPago_pag.addItem("")
        self.label2_pag = QtWidgets.QLabel(self.tab_Pagos)
        self.label2_pag.setGeometry(QtCore.QRect(200, 310, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label2_pag.setFont(font)
        self.label2_pag.setObjectName("label2_pag")
        self.line1_pag = QtWidgets.QFrame(self.tab_Pagos)
        self.line1_pag.setGeometry(QtCore.QRect(0, 270, 1161, 16))
        self.line1_pag.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1_pag.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1_pag.setObjectName("line1_pag")
        self.twMenu.addTab(self.tab_Pagos, "")
        self.tab_Productos = QtWidgets.QWidget()
        self.tab_Productos.setObjectName("tab_Productos")
        self.tvProductos_p = QtWidgets.QTableView(self.tab_Productos)
        self.tvProductos_p.setGeometry(QtCore.QRect(10, 60, 1141, 192))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tvProductos_p.setFont(font)
        self.tvProductos_p.setObjectName("tvProductos_p")
        self.cbFilterProducto_p = QtWidgets.QComboBox(self.tab_Productos)
        self.cbFilterProducto_p.setGeometry(QtCore.QRect(20, 20, 91, 22))
        self.cbFilterProducto_p.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.cbFilterProducto_p.setObjectName("cbFilterProducto_p")
        self.cbFilterProducto_p.addItem("")
        self.cbFilterProducto_p.addItem("")
        self.cbFilterProducto_p.addItem("")
        self.cbFilterProducto_p.addItem("")
        self.txtFilterProductos_p = QtWidgets.QLineEdit(self.tab_Productos)
        self.txtFilterProductos_p.setGeometry(QtCore.QRect(150, 20, 201, 20))
        self.txtFilterProductos_p.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtFilterProductos_p.setObjectName("txtFilterProductos_p")
        self.line1_p = QtWidgets.QFrame(self.tab_Productos)
        self.line1_p.setGeometry(QtCore.QRect(0, 260, 1171, 20))
        self.line1_p.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1_p.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1_p.setObjectName("line1_p")
        self.btnBorrar_p = QtWidgets.QPushButton(self.tab_Productos)
        self.btnBorrar_p.setEnabled(False)
        self.btnBorrar_p.setGeometry(QtCore.QRect(1050, 490, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnBorrar_p.setFont(font)
        self.btnBorrar_p.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnBorrar_p.setIcon(icon3)
        self.btnBorrar_p.setIconSize(QtCore.QSize(20, 20))
        self.btnBorrar_p.setObjectName("btnBorrar_p")
        self.btnModificar_p = QtWidgets.QPushButton(self.tab_Productos)
        self.btnModificar_p.setEnabled(False)
        self.btnModificar_p.setGeometry(QtCore.QRect(930, 490, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnModificar_p.setFont(font)
        self.btnModificar_p.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Img/actualizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnModificar_p.setIcon(icon4)
        self.btnModificar_p.setIconSize(QtCore.QSize(20, 20))
        self.btnModificar_p.setObjectName("btnModificar_p")
        self.btnAgregar_p = QtWidgets.QPushButton(self.tab_Productos)
        self.btnAgregar_p.setGeometry(QtCore.QRect(820, 490, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnAgregar_p.setFont(font)
        self.btnAgregar_p.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../Img/agregar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAgregar_p.setIcon(icon5)
        self.btnAgregar_p.setIconSize(QtCore.QSize(20, 20))
        self.btnAgregar_p.setObjectName("btnAgregar_p")
        self.btnGuardar_p = QtWidgets.QPushButton(self.tab_Productos)
        self.btnGuardar_p.setEnabled(False)
        self.btnGuardar_p.setGeometry(QtCore.QRect(700, 490, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnGuardar_p.setFont(font)
        self.btnGuardar_p.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnGuardar_p.setIcon(icon2)
        self.btnGuardar_p.setIconSize(QtCore.QSize(20, 20))
        self.btnGuardar_p.setObjectName("btnGuardar_p")
        self.wDatosProducto = QtWidgets.QWidget(self.tab_Productos)
        self.wDatosProducto.setEnabled(False)
        self.wDatosProducto.setGeometry(QtCore.QRect(10, 310, 1141, 171))
        self.wDatosProducto.setObjectName("wDatosProducto")
        self.label2_p = QtWidgets.QLabel(self.wDatosProducto)
        self.label2_p.setGeometry(QtCore.QRect(5, 70, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label2_p.setFont(font)
        self.label2_p.setObjectName("label2_p")
        self.label8_p = QtWidgets.QLabel(self.wDatosProducto)
        self.label8_p.setGeometry(QtCore.QRect(323, 120, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label8_p.setFont(font)
        self.label8_p.setObjectName("label8_p")
        self.label1_p = QtWidgets.QLabel(self.wDatosProducto)
        self.label1_p.setGeometry(QtCore.QRect(47, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label1_p.setFont(font)
        self.label1_p.setObjectName("label1_p")
        self.label6_p = QtWidgets.QLabel(self.wDatosProducto)
        self.label6_p.setGeometry(QtCore.QRect(315, 20, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label6_p.setFont(font)
        self.label6_p.setObjectName("label6_p")
        self.sbCantidad_p = QtWidgets.QSpinBox(self.wDatosProducto)
        self.sbCantidad_p.setGeometry(QtCore.QRect(420, 20, 131, 22))
        self.sbCantidad_p.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.sbCantidad_p.setObjectName("sbCantidad_p")
        self.btnMarca_p = QtWidgets.QPushButton(self.wDatosProducto)
        self.btnMarca_p.setGeometry(QtCore.QRect(550, 70, 21, 23))
        self.btnMarca_p.setText("")
        self.btnMarca_p.setIcon(icon)
        self.btnMarca_p.setObjectName("btnMarca_p")
        self.txtPrecioVenta_p = QtWidgets.QLineEdit(self.wDatosProducto)
        self.txtPrecioVenta_p.setGeometry(QtCore.QRect(200, 120, 71, 21))
        self.txtPrecioVenta_p.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtPrecioVenta_p.setObjectName("txtPrecioVenta_p")
        self.txtPrecioCompra_p = QtWidgets.QLineEdit(self.wDatosProducto)
        self.txtPrecioCompra_p.setGeometry(QtCore.QRect(200, 70, 71, 21))
        self.txtPrecioCompra_p.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtPrecioCompra_p.setObjectName("txtPrecioCompra_p")
        self.label10_p = QtWidgets.QLabel(self.wDatosProducto)
        self.label10_p.setGeometry(QtCore.QRect(597, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label10_p.setFont(font)
        self.label10_p.setObjectName("label10_p")
        self.txtPrecioModelo_p = QtWidgets.QLineEdit(self.wDatosProducto)
        self.txtPrecioModelo_p.setGeometry(QtCore.QRect(420, 120, 131, 21))
        self.txtPrecioModelo_p.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtPrecioModelo_p.setObjectName("txtPrecioModelo_p")
        self.txtRubro_p = QtWidgets.QLineEdit(self.wDatosProducto)
        self.txtRubro_p.setGeometry(QtCore.QRect(700, 70, 131, 21))
        self.txtRubro_p.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtRubro_p.setObjectName("txtRubro_p")
        self.rbMasculino_p = QtWidgets.QRadioButton(self.wDatosProducto)
        self.rbMasculino_p.setGeometry(QtCore.QRect(1070, 20, 41, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.rbMasculino_p.setFont(font)
        self.rbMasculino_p.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.rbMasculino_p.setObjectName("rbMasculino_p")
        self.label3_p = QtWidgets.QLabel(self.wDatosProducto)
        self.label3_p.setGeometry(QtCore.QRect(160, 70, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label3_p.setFont(font)
        self.label3_p.setObjectName("label3_p")
        self.rbFemenino_p = QtWidgets.QRadioButton(self.wDatosProducto)
        self.rbFemenino_p.setGeometry(QtCore.QRect(1010, 20, 41, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.rbFemenino_p.setFont(font)
        self.rbFemenino_p.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.rbFemenino_p.setObjectName("rbFemenino_p")
        self.txtPrecioMarca_p = QtWidgets.QLineEdit(self.wDatosProducto)
        self.txtPrecioMarca_p.setGeometry(QtCore.QRect(420, 70, 131, 21))
        self.txtPrecioMarca_p.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtPrecioMarca_p.setObjectName("txtPrecioMarca_p")
        self.label7_p = QtWidgets.QLabel(self.wDatosProducto)
        self.label7_p.setGeometry(QtCore.QRect(334, 70, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label7_p.setFont(font)
        self.label7_p.setObjectName("label7_p")
        self.txtTipo_p = QtWidgets.QLineEdit(self.wDatosProducto)
        self.txtTipo_p.setGeometry(QtCore.QRect(700, 120, 131, 21))
        self.txtTipo_p.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtTipo_p.setObjectName("txtTipo_p")
        self.label12_p = QtWidgets.QLabel(self.wDatosProducto)
        self.label12_p.setGeometry(QtCore.QRect(634, 120, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label12_p.setFont(font)
        self.label12_p.setObjectName("label12_p")
        self.label4_p = QtWidgets.QLabel(self.wDatosProducto)
        self.label4_p.setGeometry(QtCore.QRect(20, 120, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label4_p.setFont(font)
        self.label4_p.setObjectName("label4_p")
        self.txtNombre_p = QtWidgets.QLineEdit(self.wDatosProducto)
        self.txtNombre_p.setGeometry(QtCore.QRect(140, 20, 131, 21))
        self.txtNombre_p.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtNombre_p.setObjectName("txtNombre_p")
        self.label5_p = QtWidgets.QLabel(self.wDatosProducto)
        self.label5_p.setGeometry(QtCore.QRect(160, 120, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label5_p.setFont(font)
        self.label5_p.setObjectName("label5_p")
        self.btnRubro_p = QtWidgets.QPushButton(self.wDatosProducto)
        self.btnRubro_p.setGeometry(QtCore.QRect(830, 70, 21, 23))
        self.btnRubro_p.setText("")
        self.btnRubro_p.setIcon(icon)
        self.btnRubro_p.setObjectName("btnRubro_p")
        self.txtDescripcion_p = QtWidgets.QTextEdit(self.wDatosProducto)
        self.txtDescripcion_p.setGeometry(QtCore.QRect(910, 100, 221, 61))
        self.txtDescripcion_p.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtDescripcion_p.setObjectName("txtDescripcion_p")
        self.txtProveedor_p = QtWidgets.QLineEdit(self.wDatosProducto)
        self.txtProveedor_p.setGeometry(QtCore.QRect(700, 20, 131, 21))
        self.txtProveedor_p.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtProveedor_p.setObjectName("txtProveedor_p")
        self.label11_p = QtWidgets.QLabel(self.wDatosProducto)
        self.label11_p.setGeometry(QtCore.QRect(625, 70, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label11_p.setFont(font)
        self.label11_p.setObjectName("label11_p")
        self.label13_p = QtWidgets.QLabel(self.wDatosProducto)
        self.label13_p.setGeometry(QtCore.QRect(922, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label13_p.setFont(font)
        self.label13_p.setObjectName("label13_p")
        self.label14_p = QtWidgets.QLabel(self.wDatosProducto)
        self.label14_p.setGeometry(QtCore.QRect(877, 70, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label14_p.setFont(font)
        self.label14_p.setObjectName("label14_p")
        self.twMenu.addTab(self.tab_Productos, "")
        self.tab_Clientes = QtWidgets.QWidget()
        self.tab_Clientes.setObjectName("tab_Clientes")
        self.txtFilterClientes_c = QtWidgets.QLineEdit(self.tab_Clientes)
        self.txtFilterClientes_c.setGeometry(QtCore.QRect(150, 20, 201, 20))
        self.txtFilterClientes_c.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtFilterClientes_c.setObjectName("txtFilterClientes_c")
        self.cbFilterClientes_c = QtWidgets.QComboBox(self.tab_Clientes)
        self.cbFilterClientes_c.setGeometry(QtCore.QRect(20, 20, 91, 22))
        self.cbFilterClientes_c.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.cbFilterClientes_c.setObjectName("cbFilterClientes_c")
        self.cbFilterClientes_c.addItem("")
        self.cbFilterClientes_c.addItem("")
        self.line1_c = QtWidgets.QFrame(self.tab_Clientes)
        self.line1_c.setGeometry(QtCore.QRect(0, 260, 1171, 20))
        self.line1_c.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1_c.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1_c.setObjectName("line1_c")
        self.tvClientes_c = QtWidgets.QTableView(self.tab_Clientes)
        self.tvClientes_c.setGeometry(QtCore.QRect(10, 60, 1141, 192))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tvClientes_c.setFont(font)
        self.tvClientes_c.setObjectName("tvClientes_c")
        self.btnBorrar_c = QtWidgets.QPushButton(self.tab_Clientes)
        self.btnBorrar_c.setEnabled(False)
        self.btnBorrar_c.setGeometry(QtCore.QRect(1050, 490, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnBorrar_c.setFont(font)
        self.btnBorrar_c.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnBorrar_c.setIcon(icon3)
        self.btnBorrar_c.setIconSize(QtCore.QSize(20, 20))
        self.btnBorrar_c.setObjectName("btnBorrar_c")
        self.btnGuardar_c = QtWidgets.QPushButton(self.tab_Clientes)
        self.btnGuardar_c.setEnabled(False)
        self.btnGuardar_c.setGeometry(QtCore.QRect(700, 490, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnGuardar_c.setFont(font)
        self.btnGuardar_c.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnGuardar_c.setIcon(icon2)
        self.btnGuardar_c.setIconSize(QtCore.QSize(20, 20))
        self.btnGuardar_c.setObjectName("btnGuardar_c")
        self.btnAgregar_c = QtWidgets.QPushButton(self.tab_Clientes)
        self.btnAgregar_c.setGeometry(QtCore.QRect(820, 490, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnAgregar_c.setFont(font)
        self.btnAgregar_c.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnAgregar_c.setIcon(icon5)
        self.btnAgregar_c.setIconSize(QtCore.QSize(20, 20))
        self.btnAgregar_c.setObjectName("btnAgregar_c")
        self.btnModificar_c = QtWidgets.QPushButton(self.tab_Clientes)
        self.btnModificar_c.setEnabled(False)
        self.btnModificar_c.setGeometry(QtCore.QRect(930, 490, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnModificar_c.setFont(font)
        self.btnModificar_c.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnModificar_c.setIcon(icon4)
        self.btnModificar_c.setIconSize(QtCore.QSize(20, 20))
        self.btnModificar_c.setObjectName("btnModificar_c")
        self.wDatosCliente = QtWidgets.QWidget(self.tab_Clientes)
        self.wDatosCliente.setEnabled(False)
        self.wDatosCliente.setGeometry(QtCore.QRect(10, 310, 1141, 171))
        self.wDatosCliente.setObjectName("wDatosCliente")
        self.txtApellido_c = QtWidgets.QLineEdit(self.wDatosCliente)
        self.txtApellido_c.setGeometry(QtCore.QRect(140, 80, 171, 21))
        self.txtApellido_c.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtApellido_c.setObjectName("txtApellido_c")
        self.txtDPiso_c = QtWidgets.QLineEdit(self.wDatosCliente)
        self.txtDPiso_c.setGeometry(QtCore.QRect(708, 80, 31, 21))
        self.txtDPiso_c.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtDPiso_c.setObjectName("txtDPiso_c")
        self.label7_c = QtWidgets.QLabel(self.wDatosCliente)
        self.label7_c.setGeometry(QtCore.QRect(745, 80, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label7_c.setFont(font)
        self.label7_c.setObjectName("label7_c")
        self.btnSumarTelefono_c = QtWidgets.QPushButton(self.wDatosCliente)
        self.btnSumarTelefono_c.setEnabled(False)
        self.btnSumarTelefono_c.setGeometry(QtCore.QRect(1110, 20, 21, 23))
        self.btnSumarTelefono_c.setText("")
        self.btnSumarTelefono_c.setIcon(icon)
        self.btnSumarTelefono_c.setObjectName("btnSumarTelefono_c")
        self.label1_c = QtWidgets.QLabel(self.wDatosCliente)
        self.label1_c.setGeometry(QtCore.QRect(40, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label1_c.setFont(font)
        self.label1_c.setObjectName("label1_c")
        self.label5_c = QtWidgets.QLabel(self.wDatosCliente)
        self.label5_c.setGeometry(QtCore.QRect(596, 80, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label5_c.setFont(font)
        self.label5_c.setObjectName("label5_c")
        self.btnRestarTelefono_c = QtWidgets.QPushButton(self.wDatosCliente)
        self.btnRestarTelefono_c.setGeometry(QtCore.QRect(1110, 110, 21, 23))
        self.btnRestarTelefono_c.setText("")
        self.btnRestarTelefono_c.setIcon(icon1)
        self.btnRestarTelefono_c.setObjectName("btnRestarTelefono_c")
        self.txtDDpto_c = QtWidgets.QLineEdit(self.wDatosCliente)
        self.txtDDpto_c.setGeometry(QtCore.QRect(780, 80, 31, 21))
        self.txtDDpto_c.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtDDpto_c.setObjectName("txtDDpto_c")
        self.txtDNumero_c = QtWidgets.QLineEdit(self.wDatosCliente)
        self.txtDNumero_c.setGeometry(QtCore.QRect(630, 80, 41, 21))
        self.txtDNumero_c.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtDNumero_c.setObjectName("txtDNumero_c")
        self.txtNombre_c = QtWidgets.QLineEdit(self.wDatosCliente)
        self.txtNombre_c.setGeometry(QtCore.QRect(140, 20, 171, 21))
        self.txtNombre_c.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtNombre_c.setObjectName("txtNombre_c")
        self.label2_c = QtWidgets.QLabel(self.wDatosCliente)
        self.label2_c.setGeometry(QtCore.QRect(38, 80, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label2_c.setFont(font)
        self.label2_c.setObjectName("label2_c")
        self.label3_c = QtWidgets.QLabel(self.wDatosCliente)
        self.label3_c.setGeometry(QtCore.QRect(368, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label3_c.setFont(font)
        self.label3_c.setObjectName("label3_c")
        self.tvTelefonos_c = QtWidgets.QTableView(self.wDatosCliente)
        self.tvTelefonos_c.setGeometry(QtCore.QRect(870, 80, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tvTelefonos_c.setFont(font)
        self.tvTelefonos_c.setObjectName("tvTelefonos_c")
        self.txtDireccion_c = QtWidgets.QLineEdit(self.wDatosCliente)
        self.txtDireccion_c.setGeometry(QtCore.QRect(440, 80, 151, 21))
        self.txtDireccion_c.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtDireccion_c.setObjectName("txtDireccion_c")
        self.label6_c = QtWidgets.QLabel(self.wDatosCliente)
        self.label6_c.setGeometry(QtCore.QRect(675, 80, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label6_c.setFont(font)
        self.label6_c.setObjectName("label6_c")
        self.label8_c = QtWidgets.QLabel(self.wDatosCliente)
        self.label8_c.setGeometry(QtCore.QRect(858, 18, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label8_c.setFont(font)
        self.label8_c.setObjectName("label8_c")
        self.txtTelefono_c = QtWidgets.QLineEdit(self.wDatosCliente)
        self.txtTelefono_c.setGeometry(QtCore.QRect(960, 20, 141, 21))
        self.txtTelefono_c.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtTelefono_c.setObjectName("txtTelefono_c")
        self.txtEmail_c = QtWidgets.QLineEdit(self.wDatosCliente)
        self.txtEmail_c.setGeometry(QtCore.QRect(440, 20, 371, 21))
        self.txtEmail_c.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtEmail_c.setObjectName("txtEmail_c")
        self.label4_c = QtWidgets.QLabel(self.wDatosCliente)
        self.label4_c.setGeometry(QtCore.QRect(341, 80, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label4_c.setFont(font)
        self.label4_c.setObjectName("label4_c")
        self.btnCel_c = QtWidgets.QPushButton(self.wDatosCliente)
        self.btnCel_c.setGeometry(QtCore.QRect(1040, 50, 21, 23))
        self.btnCel_c.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../Img/icon-cel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCel_c.setIcon(icon6)
        self.btnCel_c.setObjectName("btnCel_c")
        self.btnFax_c = QtWidgets.QPushButton(self.wDatosCliente)
        self.btnFax_c.setGeometry(QtCore.QRect(1070, 50, 21, 23))
        self.btnFax_c.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../Img/icon-fax.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFax_c.setIcon(icon7)
        self.btnFax_c.setObjectName("btnFax_c")
        self.btnTel_c = QtWidgets.QPushButton(self.wDatosCliente)
        self.btnTel_c.setGeometry(QtCore.QRect(1010, 50, 21, 23))
        self.btnTel_c.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../Img/icon-tel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTel_c.setIcon(icon8)
        self.btnTel_c.setObjectName("btnTel_c")
        self.twMenu.addTab(self.tab_Clientes, "")
        self.tab_Proovedores = QtWidgets.QWidget()
        self.tab_Proovedores.setObjectName("tab_Proovedores")
        self.cbFilterProveedores_prov = QtWidgets.QComboBox(self.tab_Proovedores)
        self.cbFilterProveedores_prov.setGeometry(QtCore.QRect(20, 20, 91, 22))
        self.cbFilterProveedores_prov.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.cbFilterProveedores_prov.setObjectName("cbFilterProveedores_prov")
        self.cbFilterProveedores_prov.addItem("")
        self.cbFilterProveedores_prov.addItem("")
        self.tvProveedores_prov = QtWidgets.QTableView(self.tab_Proovedores)
        self.tvProveedores_prov.setGeometry(QtCore.QRect(10, 60, 1141, 192))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tvProveedores_prov.setFont(font)
        self.tvProveedores_prov.setObjectName("tvProveedores_prov")
        self.line1_prov = QtWidgets.QFrame(self.tab_Proovedores)
        self.line1_prov.setGeometry(QtCore.QRect(0, 260, 1171, 20))
        self.line1_prov.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1_prov.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1_prov.setObjectName("line1_prov")
        self.txtFilterProveedores_prov = QtWidgets.QLineEdit(self.tab_Proovedores)
        self.txtFilterProveedores_prov.setGeometry(QtCore.QRect(150, 20, 201, 20))
        self.txtFilterProveedores_prov.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtFilterProveedores_prov.setObjectName("txtFilterProveedores_prov")
        self.btnBorrar_prov = QtWidgets.QPushButton(self.tab_Proovedores)
        self.btnBorrar_prov.setEnabled(False)
        self.btnBorrar_prov.setGeometry(QtCore.QRect(1050, 490, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnBorrar_prov.setFont(font)
        self.btnBorrar_prov.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnBorrar_prov.setIcon(icon3)
        self.btnBorrar_prov.setIconSize(QtCore.QSize(20, 20))
        self.btnBorrar_prov.setObjectName("btnBorrar_prov")
        self.btnGuardar_prov = QtWidgets.QPushButton(self.tab_Proovedores)
        self.btnGuardar_prov.setEnabled(False)
        self.btnGuardar_prov.setGeometry(QtCore.QRect(700, 490, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnGuardar_prov.setFont(font)
        self.btnGuardar_prov.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnGuardar_prov.setIcon(icon2)
        self.btnGuardar_prov.setIconSize(QtCore.QSize(20, 20))
        self.btnGuardar_prov.setObjectName("btnGuardar_prov")
        self.btnAgregar_prov = QtWidgets.QPushButton(self.tab_Proovedores)
        self.btnAgregar_prov.setGeometry(QtCore.QRect(820, 490, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnAgregar_prov.setFont(font)
        self.btnAgregar_prov.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnAgregar_prov.setIcon(icon5)
        self.btnAgregar_prov.setIconSize(QtCore.QSize(20, 20))
        self.btnAgregar_prov.setObjectName("btnAgregar_prov")
        self.btnModificar_prov = QtWidgets.QPushButton(self.tab_Proovedores)
        self.btnModificar_prov.setEnabled(False)
        self.btnModificar_prov.setGeometry(QtCore.QRect(930, 490, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnModificar_prov.setFont(font)
        self.btnModificar_prov.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnModificar_prov.setIcon(icon4)
        self.btnModificar_prov.setIconSize(QtCore.QSize(20, 20))
        self.btnModificar_prov.setObjectName("btnModificar_prov")
        self.wDatosProveedor = QtWidgets.QWidget(self.tab_Proovedores)
        self.wDatosProveedor.setEnabled(False)
        self.wDatosProveedor.setGeometry(QtCore.QRect(10, 310, 1131, 171))
        self.wDatosProveedor.setObjectName("wDatosProveedor")
        self.label8_prov = QtWidgets.QLabel(self.wDatosProveedor)
        self.label8_prov.setGeometry(QtCore.QRect(858, 18, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label8_prov.setFont(font)
        self.label8_prov.setObjectName("label8_prov")
        self.label5_prov = QtWidgets.QLabel(self.wDatosProveedor)
        self.label5_prov.setGeometry(QtCore.QRect(596, 80, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label5_prov.setFont(font)
        self.label5_prov.setObjectName("label5_prov")
        self.btnSumarTelefono_prov = QtWidgets.QPushButton(self.wDatosProveedor)
        self.btnSumarTelefono_prov.setEnabled(False)
        self.btnSumarTelefono_prov.setGeometry(QtCore.QRect(1110, 20, 21, 23))
        self.btnSumarTelefono_prov.setText("")
        self.btnSumarTelefono_prov.setIcon(icon)
        self.btnSumarTelefono_prov.setObjectName("btnSumarTelefono_prov")
        self.txtNombre_prov = QtWidgets.QLineEdit(self.wDatosProveedor)
        self.txtNombre_prov.setGeometry(QtCore.QRect(140, 20, 171, 21))
        self.txtNombre_prov.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtNombre_prov.setObjectName("txtNombre_prov")
        self.txtDNumero_prov = QtWidgets.QLineEdit(self.wDatosProveedor)
        self.txtDNumero_prov.setGeometry(QtCore.QRect(630, 80, 41, 21))
        self.txtDNumero_prov.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtDNumero_prov.setObjectName("txtDNumero_prov")
        self.txtDireccion_prov = QtWidgets.QLineEdit(self.wDatosProveedor)
        self.txtDireccion_prov.setGeometry(QtCore.QRect(440, 80, 151, 21))
        self.txtDireccion_prov.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtDireccion_prov.setObjectName("txtDireccion_prov")
        self.txtDPiso_prov = QtWidgets.QLineEdit(self.wDatosProveedor)
        self.txtDPiso_prov.setGeometry(QtCore.QRect(708, 80, 31, 21))
        self.txtDPiso_prov.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtDPiso_prov.setObjectName("txtDPiso_prov")
        self.txtEmail_prov = QtWidgets.QLineEdit(self.wDatosProveedor)
        self.txtEmail_prov.setGeometry(QtCore.QRect(440, 20, 371, 21))
        self.txtEmail_prov.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtEmail_prov.setObjectName("txtEmail_prov")
        self.label3_prov = QtWidgets.QLabel(self.wDatosProveedor)
        self.label3_prov.setGeometry(QtCore.QRect(368, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label3_prov.setFont(font)
        self.label3_prov.setObjectName("label3_prov")
        self.label1_prov = QtWidgets.QLabel(self.wDatosProveedor)
        self.label1_prov.setGeometry(QtCore.QRect(40, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label1_prov.setFont(font)
        self.label1_prov.setObjectName("label1_prov")
        self.label6_prov = QtWidgets.QLabel(self.wDatosProveedor)
        self.label6_prov.setGeometry(QtCore.QRect(675, 80, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label6_prov.setFont(font)
        self.label6_prov.setObjectName("label6_prov")
        self.txtDDpto_prov = QtWidgets.QLineEdit(self.wDatosProveedor)
        self.txtDDpto_prov.setGeometry(QtCore.QRect(780, 80, 31, 21))
        self.txtDDpto_prov.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtDDpto_prov.setObjectName("txtDDpto_prov")
        self.txtDescripcion_prov = QtWidgets.QLineEdit(self.wDatosProveedor)
        self.txtDescripcion_prov.setGeometry(QtCore.QRect(140, 80, 171, 21))
        self.txtDescripcion_prov.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtDescripcion_prov.setObjectName("txtDescripcion_prov")
        self.label4_prov = QtWidgets.QLabel(self.wDatosProveedor)
        self.label4_prov.setGeometry(QtCore.QRect(342, 80, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label4_prov.setFont(font)
        self.label4_prov.setObjectName("label4_prov")
        self.label7_prov = QtWidgets.QLabel(self.wDatosProveedor)
        self.label7_prov.setGeometry(QtCore.QRect(745, 80, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label7_prov.setFont(font)
        self.label7_prov.setObjectName("label7_prov")
        self.tvTelefonos_prov = QtWidgets.QTableView(self.wDatosProveedor)
        self.tvTelefonos_prov.setGeometry(QtCore.QRect(870, 80, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tvTelefonos_prov.setFont(font)
        self.tvTelefonos_prov.setObjectName("tvTelefonos_prov")
        self.label2_prov = QtWidgets.QLabel(self.wDatosProveedor)
        self.label2_prov.setGeometry(QtCore.QRect(18, 80, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label2_prov.setFont(font)
        self.label2_prov.setObjectName("label2_prov")
        self.btnRestarTelefono_prov = QtWidgets.QPushButton(self.wDatosProveedor)
        self.btnRestarTelefono_prov.setGeometry(QtCore.QRect(1110, 110, 21, 23))
        self.btnRestarTelefono_prov.setText("")
        self.btnRestarTelefono_prov.setIcon(icon1)
        self.btnRestarTelefono_prov.setObjectName("btnRestarTelefono_prov")
        self.txtTelefono_prov = QtWidgets.QLineEdit(self.wDatosProveedor)
        self.txtTelefono_prov.setGeometry(QtCore.QRect(960, 20, 141, 21))
        self.txtTelefono_prov.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtTelefono_prov.setObjectName("txtTelefono_prov")
        self.label1_prov_2 = QtWidgets.QLabel(self.wDatosProveedor)
        self.label1_prov_2.setGeometry(QtCore.QRect(63, 130, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label1_prov_2.setFont(font)
        self.label1_prov_2.setObjectName("label1_prov_2")
        self.txtWeb_prov = QtWidgets.QLineEdit(self.wDatosProveedor)
        self.txtWeb_prov.setGeometry(QtCore.QRect(140, 130, 351, 21))
        self.txtWeb_prov.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtWeb_prov.setObjectName("txtWeb_prov")
        self.btnTel_prov = QtWidgets.QPushButton(self.wDatosProveedor)
        self.btnTel_prov.setGeometry(QtCore.QRect(1010, 50, 21, 23))
        self.btnTel_prov.setText("")
        self.btnTel_prov.setIcon(icon8)
        self.btnTel_prov.setObjectName("btnTel_prov")
        self.btnCel_prov = QtWidgets.QPushButton(self.wDatosProveedor)
        self.btnCel_prov.setGeometry(QtCore.QRect(1040, 50, 21, 23))
        self.btnCel_prov.setText("")
        self.btnCel_prov.setIcon(icon6)
        self.btnCel_prov.setObjectName("btnCel_prov")
        self.btnFax_prov = QtWidgets.QPushButton(self.wDatosProveedor)
        self.btnFax_prov.setGeometry(QtCore.QRect(1070, 50, 21, 23))
        self.btnFax_prov.setText("")
        self.btnFax_prov.setIcon(icon7)
        self.btnFax_prov.setObjectName("btnFax_prov")
        self.twMenu.addTab(self.tab_Proovedores, "")
        self.tab_Usuarios = QtWidgets.QWidget()
        self.tab_Usuarios.setObjectName("tab_Usuarios")
        self.txtFilterUsuario_u = QtWidgets.QLineEdit(self.tab_Usuarios)
        self.txtFilterUsuario_u.setGeometry(QtCore.QRect(150, 20, 201, 20))
        self.txtFilterUsuario_u.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtFilterUsuario_u.setObjectName("txtFilterUsuario_u")
        self.btnGuardar_u = QtWidgets.QPushButton(self.tab_Usuarios)
        self.btnGuardar_u.setEnabled(False)
        self.btnGuardar_u.setGeometry(QtCore.QRect(700, 490, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnGuardar_u.setFont(font)
        self.btnGuardar_u.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnGuardar_u.setIcon(icon2)
        self.btnGuardar_u.setIconSize(QtCore.QSize(20, 20))
        self.btnGuardar_u.setObjectName("btnGuardar_u")
        self.cbFilterUsuario_u = QtWidgets.QComboBox(self.tab_Usuarios)
        self.cbFilterUsuario_u.setGeometry(QtCore.QRect(20, 20, 91, 22))
        self.cbFilterUsuario_u.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.cbFilterUsuario_u.setObjectName("cbFilterUsuario_u")
        self.cbFilterUsuario_u.addItem("")
        self.cbFilterUsuario_u.addItem("")
        self.cbFilterUsuario_u.addItem("")
        self.tvUsuarios_u = QtWidgets.QTableView(self.tab_Usuarios)
        self.tvUsuarios_u.setGeometry(QtCore.QRect(10, 60, 1141, 192))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tvUsuarios_u.setFont(font)
        self.tvUsuarios_u.setObjectName("tvUsuarios_u")
        self.btnAgregar_u = QtWidgets.QPushButton(self.tab_Usuarios)
        self.btnAgregar_u.setGeometry(QtCore.QRect(820, 490, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnAgregar_u.setFont(font)
        self.btnAgregar_u.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnAgregar_u.setIcon(icon5)
        self.btnAgregar_u.setIconSize(QtCore.QSize(20, 20))
        self.btnAgregar_u.setObjectName("btnAgregar_u")
        self.line1_u = QtWidgets.QFrame(self.tab_Usuarios)
        self.line1_u.setGeometry(QtCore.QRect(0, 260, 1171, 20))
        self.line1_u.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1_u.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1_u.setObjectName("line1_u")
        self.btnModificar_u = QtWidgets.QPushButton(self.tab_Usuarios)
        self.btnModificar_u.setEnabled(False)
        self.btnModificar_u.setGeometry(QtCore.QRect(930, 490, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnModificar_u.setFont(font)
        self.btnModificar_u.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnModificar_u.setIcon(icon4)
        self.btnModificar_u.setIconSize(QtCore.QSize(20, 20))
        self.btnModificar_u.setObjectName("btnModificar_u")
        self.btnBorrar_u = QtWidgets.QPushButton(self.tab_Usuarios)
        self.btnBorrar_u.setEnabled(False)
        self.btnBorrar_u.setGeometry(QtCore.QRect(1050, 490, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnBorrar_u.setFont(font)
        self.btnBorrar_u.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnBorrar_u.setIcon(icon3)
        self.btnBorrar_u.setIconSize(QtCore.QSize(20, 20))
        self.btnBorrar_u.setObjectName("btnBorrar_u")
        self.wDatosUsuario = QtWidgets.QWidget(self.tab_Usuarios)
        self.wDatosUsuario.setEnabled(False)
        self.wDatosUsuario.setGeometry(QtCore.QRect(10, 310, 1141, 171))
        self.wDatosUsuario.setObjectName("wDatosUsuario")
        self.label5_u = QtWidgets.QLabel(self.wDatosUsuario)
        self.label5_u.setGeometry(QtCore.QRect(342, 80, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label5_u.setFont(font)
        self.label5_u.setObjectName("label5_u")
        self.label1_u = QtWidgets.QLabel(self.wDatosUsuario)
        self.label1_u.setGeometry(QtCore.QRect(40, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label1_u.setFont(font)
        self.label1_u.setObjectName("label1_u")
        self.txtNombre_u = QtWidgets.QLineEdit(self.wDatosUsuario)
        self.txtNombre_u.setGeometry(QtCore.QRect(140, 20, 171, 21))
        self.txtNombre_u.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtNombre_u.setObjectName("txtNombre_u")
        self.txtDireccion_u = QtWidgets.QLineEdit(self.wDatosUsuario)
        self.txtDireccion_u.setGeometry(QtCore.QRect(440, 80, 151, 21))
        self.txtDireccion_u.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtDireccion_u.setObjectName("txtDireccion_u")
        self.txtApellido_u = QtWidgets.QLineEdit(self.wDatosUsuario)
        self.txtApellido_u.setGeometry(QtCore.QRect(140, 80, 171, 21))
        self.txtApellido_u.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtApellido_u.setObjectName("txtApellido_u")
        self.cbTipoUsuario_u = QtWidgets.QComboBox(self.wDatosUsuario)
        self.cbTipoUsuario_u.setGeometry(QtCore.QRect(757, 140, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.cbTipoUsuario_u.setFont(font)
        self.cbTipoUsuario_u.setObjectName("cbTipoUsuario_u")
        self.cbTipoUsuario_u.addItem("")
        self.cbTipoUsuario_u.addItem("")
        self.label8_u = QtWidgets.QLabel(self.wDatosUsuario)
        self.label8_u.setGeometry(QtCore.QRect(745, 80, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label8_u.setFont(font)
        self.label8_u.setObjectName("label8_u")
        self.txtContrasena_u = QtWidgets.QLineEdit(self.wDatosUsuario)
        self.txtContrasena_u.setGeometry(QtCore.QRect(440, 140, 171, 21))
        self.txtContrasena_u.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtContrasena_u.setObjectName("txtContrasena_u")
        self.label7_u = QtWidgets.QLabel(self.wDatosUsuario)
        self.label7_u.setGeometry(QtCore.QRect(675, 80, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label7_u.setFont(font)
        self.label7_u.setObjectName("label7_u")
        self.txtDDpto_u = QtWidgets.QLineEdit(self.wDatosUsuario)
        self.txtDDpto_u.setGeometry(QtCore.QRect(780, 80, 31, 21))
        self.txtDDpto_u.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtDDpto_u.setObjectName("txtDDpto_u")
        self.label2_u = QtWidgets.QLabel(self.wDatosUsuario)
        self.label2_u.setGeometry(QtCore.QRect(39, 80, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label2_u.setFont(font)
        self.label2_u.setObjectName("label2_u")
        self.txtEmail_u = QtWidgets.QLineEdit(self.wDatosUsuario)
        self.txtEmail_u.setGeometry(QtCore.QRect(440, 20, 371, 21))
        self.txtEmail_u.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtEmail_u.setObjectName("txtEmail_u")
        self.btnSumarTelefono_u = QtWidgets.QPushButton(self.wDatosUsuario)
        self.btnSumarTelefono_u.setEnabled(False)
        self.btnSumarTelefono_u.setGeometry(QtCore.QRect(1110, 20, 21, 23))
        self.btnSumarTelefono_u.setText("")
        self.btnSumarTelefono_u.setIcon(icon)
        self.btnSumarTelefono_u.setObjectName("btnSumarTelefono_u")
        self.label3_u = QtWidgets.QLabel(self.wDatosUsuario)
        self.label3_u.setGeometry(QtCore.QRect(45, 140, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label3_u.setFont(font)
        self.label3_u.setObjectName("label3_u")
        self.label11_u = QtWidgets.QLabel(self.wDatosUsuario)
        self.label11_u.setGeometry(QtCore.QRect(858, 18, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label11_u.setFont(font)
        self.label11_u.setObjectName("label11_u")
        self.label6_u = QtWidgets.QLabel(self.wDatosUsuario)
        self.label6_u.setGeometry(QtCore.QRect(596, 80, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label6_u.setFont(font)
        self.label6_u.setObjectName("label6_u")
        self.label9_u = QtWidgets.QLabel(self.wDatosUsuario)
        self.label9_u.setGeometry(QtCore.QRect(326, 140, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label9_u.setFont(font)
        self.label9_u.setObjectName("label9_u")
        self.txtUsuario_u = QtWidgets.QLineEdit(self.wDatosUsuario)
        self.txtUsuario_u.setGeometry(QtCore.QRect(142, 140, 171, 21))
        self.txtUsuario_u.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtUsuario_u.setObjectName("txtUsuario_u")
        self.btnRestarTelefono_u = QtWidgets.QPushButton(self.wDatosUsuario)
        self.btnRestarTelefono_u.setGeometry(QtCore.QRect(1110, 110, 21, 23))
        self.btnRestarTelefono_u.setText("")
        self.btnRestarTelefono_u.setIcon(icon1)
        self.btnRestarTelefono_u.setObjectName("btnRestarTelefono_u")
        self.label4 = QtWidgets.QLabel(self.wDatosUsuario)
        self.label4.setGeometry(QtCore.QRect(368, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label4.setFont(font)
        self.label4.setObjectName("label4")
        self.txtDPiso_u = QtWidgets.QLineEdit(self.wDatosUsuario)
        self.txtDPiso_u.setGeometry(QtCore.QRect(708, 80, 31, 21))
        self.txtDPiso_u.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtDPiso_u.setObjectName("txtDPiso_u")
        self.txtDNumero_u = QtWidgets.QLineEdit(self.wDatosUsuario)
        self.txtDNumero_u.setGeometry(QtCore.QRect(630, 80, 41, 21))
        self.txtDNumero_u.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtDNumero_u.setObjectName("txtDNumero_u")
        self.label10_u = QtWidgets.QLabel(self.wDatosUsuario)
        self.label10_u.setGeometry(QtCore.QRect(650, 140, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label10_u.setFont(font)
        self.label10_u.setObjectName("label10_u")
        self.tvTelefono_u = QtWidgets.QTableView(self.wDatosUsuario)
        self.tvTelefono_u.setGeometry(QtCore.QRect(870, 80, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tvTelefono_u.setFont(font)
        self.tvTelefono_u.setObjectName("tvTelefono_u")
        self.txtTelefono_u = QtWidgets.QLineEdit(self.wDatosUsuario)
        self.txtTelefono_u.setGeometry(QtCore.QRect(960, 20, 141, 21))
        self.txtTelefono_u.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.txtTelefono_u.setObjectName("txtTelefono_u")
        self.btnTel_u = QtWidgets.QPushButton(self.wDatosUsuario)
        self.btnTel_u.setGeometry(QtCore.QRect(1010, 50, 21, 23))
        self.btnTel_u.setText("")
        self.btnTel_u.setIcon(icon8)
        self.btnTel_u.setObjectName("btnTel_u")
        self.btnCel_u = QtWidgets.QPushButton(self.wDatosUsuario)
        self.btnCel_u.setGeometry(QtCore.QRect(1040, 50, 21, 23))
        self.btnCel_u.setText("")
        self.btnCel_u.setIcon(icon6)
        self.btnCel_u.setObjectName("btnCel_u")
        self.btnFax_u = QtWidgets.QPushButton(self.wDatosUsuario)
        self.btnFax_u.setGeometry(QtCore.QRect(1070, 50, 21, 23))
        self.btnFax_u.setText("")
        self.btnFax_u.setIcon(icon7)
        self.btnFax_u.setObjectName("btnFax_u")
        self.twMenu.addTab(self.tab_Usuarios, "")
        self.tab_Estadisticas = QtWidgets.QWidget()
        self.tab_Estadisticas.setObjectName("tab_Estadisticas")
        self.twMenu.addTab(self.tab_Estadisticas, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1190, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuProbando = QtWidgets.QMenu(self.menuBar)
        self.menuProbando.setObjectName("menuProbando")
        self.menuAyuda = QtWidgets.QMenu(self.menuBar)
        self.menuAyuda.setObjectName("menuAyuda")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainToolBar.sizePolicy().hasHeightForWidth())
        self.mainToolBar.setSizePolicy(sizePolicy)
        self.mainToolBar.setAcceptDrops(False)
        self.mainToolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mainToolBar.setAutoFillBackground(True)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionManual_de_uso = QtWidgets.QAction(MainWindow)
        self.actionManual_de_uso.setObjectName("actionManual_de_uso")
        self.actionReportar_error = QtWidgets.QAction(MainWindow)
        self.actionReportar_error.setObjectName("actionReportar_error")
        self.actionTransacciones = QtWidgets.QAction(MainWindow)
        self.actionTransacciones.setObjectName("actionTransacciones")
        self.actionProductos = QtWidgets.QAction(MainWindow)
        self.actionProductos.setObjectName("actionProductos")
        self.actionClientes = QtWidgets.QAction(MainWindow)
        self.actionClientes.setObjectName("actionClientes")
        self.actionProveedores = QtWidgets.QAction(MainWindow)
        self.actionProveedores.setObjectName("actionProveedores")
        self.actionEstaditicas = QtWidgets.QAction(MainWindow)
        self.actionEstaditicas.setObjectName("actionEstaditicas")
        self.actionUsuarios = QtWidgets.QAction(MainWindow)
        self.actionUsuarios.setObjectName("actionUsuarios")
        self.actionCerrarSesion = QtWidgets.QAction(MainWindow)
        self.actionCerrarSesion.setObjectName("actionCerrarSesion")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.menuProbando.addAction(self.actionTransacciones)
        self.menuProbando.addAction(self.actionProductos)
        self.menuProbando.addAction(self.actionClientes)
        self.menuProbando.addAction(self.actionProveedores)
        self.menuProbando.addAction(self.actionEstaditicas)
        self.menuProbando.addAction(self.actionUsuarios)
        self.menuProbando.addSeparator()
        self.menuProbando.addAction(self.actionCerrarSesion)
        self.menuProbando.addSeparator()
        self.menuProbando.addAction(self.actionSalir)
        self.menuAyuda.addAction(self.actionManual_de_uso)
        self.menuAyuda.addAction(self.actionReportar_error)
        self.menuBar.addAction(self.menuProbando.menuAction())
        self.menuBar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(MainWindow)
        self.twMenu.setCurrentIndex(0)
        self.actionSalir.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rbCompra_t.setText(_translate("MainWindow", "Compra"))
        self.rbVenta_t.setText(_translate("MainWindow", "Venta"))
        self.cbFilterCliente_t.setItemText(0, _translate("MainWindow", "Apellido"))
        self.cbFilterCliente_t.setItemText(1, _translate("MainWindow", "Email"))
        self.cbFilterProducto_t.setItemText(0, _translate("MainWindow", "Nombre"))
        self.cbFilterProducto_t.setItemText(1, _translate("MainWindow", "Marca"))
        self.cbFilterProducto_t.setItemText(2, _translate("MainWindow", "Rubro"))
        self.cbFilterProducto_t.setItemText(3, _translate("MainWindow", "Precio de Venta"))
        self.btnAceptar_t.setText(_translate("MainWindow", "ACEPTAR"))
        self.btnCancelar_t.setText(_translate("MainWindow", "CANCELAR"))
        self.label1_t.setText(_translate("MainWindow", "Tipo de transaccion : "))
        self.label2_t.setText(_translate("MainWindow", "Cliente : "))
        self.label3_t.setText(_translate("MainWindow", "Producto : "))
        self.label4_t.setText(_translate("MainWindow", "Detalle Transaccion "))
        self.label5_t.setText(_translate("MainWindow", "Cantidad :"))
        self.twMenu.setTabText(self.twMenu.indexOf(self.tab_Transacciones), _translate("MainWindow", "Transacciones"))
        self.btnAceptar_pag.setText(_translate("MainWindow", "ACEPTAR"))
        self.btnCancelar_pag.setText(_translate("MainWindow", "CANCELAR"))
        self.cbFilterCliente_pag.setItemText(0, _translate("MainWindow", "Persona"))
        self.cbFilterCliente_pag.setItemText(1, _translate("MainWindow", "Fecha"))
        self.label1_pag.setText(_translate("MainWindow", "Monto :"))
        self.label4_pag.setText(_translate("MainWindow", "Detalle Transaccion :"))
        self.label3_pag.setText(_translate("MainWindow", "Forma de pago : "))
        self.cbFormaPago_pag.setItemText(0, _translate("MainWindow", "Efectivo"))
        self.cbFormaPago_pag.setItemText(1, _translate("MainWindow", "Tarjeta"))
        self.cbFormaPago_pag.setItemText(2, _translate("MainWindow", "Cheque"))
        self.label2_pag.setText(_translate("MainWindow", "$"))
        self.twMenu.setTabText(self.twMenu.indexOf(self.tab_Pagos), _translate("MainWindow", "Pagos"))
        self.cbFilterProducto_p.setItemText(0, _translate("MainWindow", "Nombre"))
        self.cbFilterProducto_p.setItemText(1, _translate("MainWindow", "Marca"))
        self.cbFilterProducto_p.setItemText(2, _translate("MainWindow", "Rubro"))
        self.cbFilterProducto_p.setItemText(3, _translate("MainWindow", "Precio Venta"))
        self.btnBorrar_p.setText(_translate("MainWindow", "BORRAR"))
        self.btnModificar_p.setText(_translate("MainWindow", "MODIFICAR"))
        self.btnAgregar_p.setText(_translate("MainWindow", "AGREGAR"))
        self.btnGuardar_p.setText(_translate("MainWindow", "GUARDAR"))
        self.label2_p.setText(_translate("MainWindow", "Precio Compra :"))
        self.label8_p.setText(_translate("MainWindow", "Modelo :"))
        self.label1_p.setText(_translate("MainWindow", "Nombre :"))
        self.label6_p.setText(_translate("MainWindow", "Cantidad :"))
        self.label10_p.setText(_translate("MainWindow", "Proveedor :"))
        self.rbMasculino_p.setText(_translate("MainWindow", "M"))
        self.label3_p.setText(_translate("MainWindow", "$"))
        self.rbFemenino_p.setText(_translate("MainWindow", "F"))
        self.label7_p.setText(_translate("MainWindow", "Marca :"))
        self.label12_p.setText(_translate("MainWindow", "Tipo :"))
        self.label4_p.setText(_translate("MainWindow", "Precio Venta :"))
        self.label5_p.setText(_translate("MainWindow", "$"))
        self.label11_p.setText(_translate("MainWindow", "Rubro :"))
        self.label13_p.setText(_translate("MainWindow", "Sexo :"))
        self.label14_p.setText(_translate("MainWindow", "Descripcion :"))
        self.twMenu.setTabText(self.twMenu.indexOf(self.tab_Productos), _translate("MainWindow", "Productos"))
        self.cbFilterClientes_c.setItemText(0, _translate("MainWindow", "Apellido"))
        self.cbFilterClientes_c.setItemText(1, _translate("MainWindow", "Email"))
        self.btnBorrar_c.setText(_translate("MainWindow", "BORRAR"))
        self.btnGuardar_c.setText(_translate("MainWindow", "GUARDAR"))
        self.btnAgregar_c.setText(_translate("MainWindow", "AGREGAR"))
        self.btnModificar_c.setText(_translate("MainWindow", "MODIFICAR"))
        self.label7_c.setText(_translate("MainWindow", "Dpto"))
        self.label1_c.setText(_translate("MainWindow", "Nombre :"))
        self.label5_c.setText(_translate("MainWindow", "Nro."))
        self.label2_c.setText(_translate("MainWindow", "Apellido :"))
        self.label3_c.setText(_translate("MainWindow", "Email :"))
        self.label6_c.setText(_translate("MainWindow", "Piso"))
        self.label8_c.setText(_translate("MainWindow", "Telefono :"))
        self.label4_c.setText(_translate("MainWindow", "Direccion :"))
        self.twMenu.setTabText(self.twMenu.indexOf(self.tab_Clientes), _translate("MainWindow", "Clientes"))
        self.cbFilterProveedores_prov.setItemText(0, _translate("MainWindow", "Descripcion"))
        self.cbFilterProveedores_prov.setItemText(1, _translate("MainWindow", "Email"))
        self.btnBorrar_prov.setText(_translate("MainWindow", "BORRAR"))
        self.btnGuardar_prov.setText(_translate("MainWindow", "GUARDAR"))
        self.btnAgregar_prov.setText(_translate("MainWindow", "AGREGAR"))
        self.btnModificar_prov.setText(_translate("MainWindow", "MODIFICAR"))
        self.label8_prov.setText(_translate("MainWindow", "Telefono :"))
        self.label5_prov.setText(_translate("MainWindow", "Nro."))
        self.label3_prov.setText(_translate("MainWindow", "Email :"))
        self.label1_prov.setText(_translate("MainWindow", "Nombre :"))
        self.label6_prov.setText(_translate("MainWindow", "Piso"))
        self.label4_prov.setText(_translate("MainWindow", "Direccion :"))
        self.label7_prov.setText(_translate("MainWindow", "Dpto"))
        self.label2_prov.setText(_translate("MainWindow", "Descripcion :"))
        self.label1_prov_2.setText(_translate("MainWindow", "Web :"))
        self.twMenu.setTabText(self.twMenu.indexOf(self.tab_Proovedores), _translate("MainWindow", "Proveedores"))
        self.btnGuardar_u.setText(_translate("MainWindow", "GUARDAR"))
        self.cbFilterUsuario_u.setItemText(0, _translate("MainWindow", "Apellido"))
        self.cbFilterUsuario_u.setItemText(1, _translate("MainWindow", "Usuario"))
        self.cbFilterUsuario_u.setItemText(2, _translate("MainWindow", "Tipo"))
        self.btnAgregar_u.setText(_translate("MainWindow", "AGREGAR"))
        self.btnModificar_u.setText(_translate("MainWindow", "MODIFICAR"))
        self.btnBorrar_u.setText(_translate("MainWindow", "BORRAR"))
        self.label5_u.setText(_translate("MainWindow", "Direccion :"))
        self.label1_u.setText(_translate("MainWindow", "Nombre :"))
        self.cbTipoUsuario_u.setItemText(0, _translate("MainWindow", "admin"))
        self.cbTipoUsuario_u.setItemText(1, _translate("MainWindow", "user"))
        self.label8_u.setText(_translate("MainWindow", "Dpto"))
        self.label7_u.setText(_translate("MainWindow", "Piso"))
        self.label2_u.setText(_translate("MainWindow", "Apellido :"))
        self.label3_u.setText(_translate("MainWindow", "Usuario : "))
        self.label11_u.setText(_translate("MainWindow", "Telefono :"))
        self.label6_u.setText(_translate("MainWindow", "Nro."))
        self.label9_u.setText(_translate("MainWindow", "Constraseña : "))
        self.label4.setText(_translate("MainWindow", "Email :"))
        self.label10_u.setText(_translate("MainWindow", "Tipo Usuario :"))
        self.twMenu.setTabText(self.twMenu.indexOf(self.tab_Usuarios), _translate("MainWindow", "Usuarios"))
        self.twMenu.setTabText(self.twMenu.indexOf(self.tab_Estadisticas), _translate("MainWindow", "Estadisticas"))
        self.menuProbando.setTitle(_translate("MainWindow", "Archivo"))
        self.menuAyuda.setTitle(_translate("MainWindow", "Ayuda"))
        self.actionManual_de_uso.setText(_translate("MainWindow", "Manual de uso"))
        self.actionReportar_error.setText(_translate("MainWindow", "Reportar error"))
        self.actionTransacciones.setText(_translate("MainWindow", "Transacciones"))
        self.actionProductos.setText(_translate("MainWindow", "Productos"))
        self.actionClientes.setText(_translate("MainWindow", "Clientes"))
        self.actionProveedores.setText(_translate("MainWindow", "Proveedores"))
        self.actionEstaditicas.setText(_translate("MainWindow", "Estaditicas"))
        self.actionUsuarios.setText(_translate("MainWindow", "Usuarios"))
        self.actionCerrarSesion.setText(_translate("MainWindow", "Cerrar Sesion"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))

